"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
"""

def euler():
	
	f = [1,2]
	i = 0
	j = 1
	while f[j] < 4000000:
		f.append( f[i] + f[j] )
		i = i + 1
		j = j + 1
	
	print f
	total = 0
	for n in f:
		if n % 2 == 0:
			print n
			total = total + n
			
	print total

if __name__ == '__main__':
    euler()